### ISSUE TITLE
2 Broken test!

### ISSUE THREAD

**Issue by Alexisvt** [Brocco/ng-conf-toh-demo#1]
Hi Brocco sorry for bother you! But Do you know Why I''m seeing the same broken test as you had in your presentations?. For me that don't make sense since the dashboard.component is a child of toh.component! Thanks for your help!

**Comment by Brocco** [comment]
I had tests running when I pushed up the code, the issue was that I was injecting in dependencies into components but was not injecting them in within the spec files. Those should all now be mocked out appropriately now. There's a bug (which should now be fixed) regarding the version of the generated project, so you may need to update that in package.json to match the globally installed version.

And no bother at all, this is why I pushed up the code. For anyone to play with. Let me know if that works for you, or provide a more detailed error.

**Comment by Alexisvt** [comment]
Thank you sir for your help! I will try to fix the problem with your provided information! And If I don't have luck I will ask you again! Thanks again!! By the way excellent work!! :100: :+1:  :)

**Comment by Brocco** [comment]
Thanks!
